FROM node:14

WORKDIR /usr/src/app
COPY . .

ARG database_url
ARG shadow_database_url
ENV DATABASE_URL=$database_url
ENV SHADOW_DATABASE_URL=$shadow_database_url

RUN yarn
RUN npx prisma generate
RUN npx prisma migrate dev

CMD [ "yarn", "start:dev" ]